changelog:
    exclude:
        labels:
            - ignore-for-release
            - auto-pr
            - dependencies
        authors:
            - app/github-actions
    categories:
        - title: Critical Changes 🛠
          labels:
              - critical-change
        - title: Changes 🎉
          labels:
              - enhancement
              - "*"
          exclude:
              labels:
                  - bug
        - title: Issues Fixed 🩴
          labels:
              - bug
