# Stubs for pygraphviz (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .agraph import AGraph as AGraph, Attribute as Attribute, DotError as DotError, Edge as Edge, ItemAttribute as ItemAttribute, Node as Node
