[tool.black]
exclude = '^/(\.|dist|pybuild|venv)'

[tool.coverage.run]
omit = ["*/tests/*", "cumulusci/files/*", ]
source = ["cumulusci", ]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@abstract", "@abc.abstract" ]

[tool.pytest.ini_options]
testpaths = "cumulusci"
addopts =  "-p cumulusci.tests.pytest_plugins.pytest_typeguard -p cumulusci.tests.pytest_plugins.pytest_sf_vcr -p cumulusci.tests.pytest_plugins.pytest_sf_orgconnect"

[tool.isort]
profile = "black"
multi_line_output = 3
skip_glob = "cumulusci/**/__init__.py"
