# Stubs for fastnumbers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from typing import overload

dig: int
max_exp: int
max_int_len: int
min_exp: int

def fast_float(
    x,
    default=...,
    raise_on_invalid=...,
    key=...,
    nan=...,
    inf=...,
    allow_underscores=...,
) -> Any: ...
def fast_real(
    x,
    default=...,
    raise_on_invalid=...,
    key=...,
    nan=...,
    inf=...,
    allow_underscores=...,
) -> Any: ...
