OUTPUT=help.md
echo "# Full help text for the cumulusci command" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## cumulusci" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci" >> "$OUTPUT"
cumulusci >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## Salesforce" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci unmanaged_deploy --help" >> "$OUTPUT"
cumulusci unmanaged_deploy --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci managed_deploy --help" >> "$OUTPUT"
cumulusci managed_deploy --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci run_tests --help" >> "$OUTPUT"
cumulusci run_tests --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci update_package_xml --help" >> "$OUTPUT"
cumulusci update_package_xml --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci package_beta --help" >> "$OUTPUT"
cumulusci package_beta --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci apextestsdb_upload --help" >> "$OUTPUT"
cumulusci apextestsdb_upload --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci github" >> "$OUTPUT"
echo "## Github" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cumulusci github >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci release --help" >> "$OUTPUT"
cumulusci github release --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci release_notes --help" >> "$OUTPUT"
cumulusci github release_notes --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci clone_tag --help" >> "$OUTPUT"
cumulusci github clone_tag --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci master_to_feature --help" >> "$OUTPUT"
cumulusci github master_to_feature --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci ci" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## Continuous Integration" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cumulusci ci >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci ci deploy --help" >> "$OUTPUT"
cumulusci ci deploy --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci ci beta_deploy --help" >> "$OUTPUT"
cumulusci ci beta_deploy --help >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$ cumulusci ci next_step --help" >> "$OUTPUT"
cumulusci ci next_step --help >> "$OUTPUT"
