OUTPUT=help.md
echo "# Full help text for the cumulusci command" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## cumulusci" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci" >> "$OUTPUT"
cumulusci | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## For Developers" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci dev apextestsdb_upload --help" >> "$OUTPUT"
cumulusci dev apextestsdb_upload --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci dev deploy --help" >> "$OUTPUT"
cumulusci dev deploy --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci dev deploy_managed --help" >> "$OUTPUT"
cumulusci dev deploy_managed --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci dev run_tests --help" >> "$OUTPUT"
cumulusci dev run_tests --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci dev update_package_xml --help" >> "$OUTPUT"
cumulusci dev update_package_xml --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## For Release Managers" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci release deploy --help" >> "$OUTPUT"
cumulusci release deploy --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci release upload_beta --help" >> "$OUTPUT"
cumulusci release upload_beta --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci github" >> "$OUTPUT"
echo "## Github" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cumulusci github | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci release --help" >> "$OUTPUT"
cumulusci github release --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci release_notes --help" >> "$OUTPUT"
cumulusci github release_notes --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci clone_tag --help" >> "$OUTPUT"
cumulusci github clone_tag --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci master_to_feature --help" >> "$OUTPUT"
cumulusci github master_to_feature --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci ci" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "## Continuous Integration" >> "$OUTPUT"
echo "" >> "$OUTPUT"
cumulusci ci | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci ci deploy --help" >> "$OUTPUT"
cumulusci ci deploy --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci ci beta_deploy --help" >> "$OUTPUT"
cumulusci ci beta_deploy --help | sed -e 's/^/    /g' >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "    $ cumulusci ci next_step --help" >> "$OUTPUT"
cumulusci ci next_step --help | sed -e 's/^/    /g' >> "$OUTPUT"
