# Hard-coded objects
- object: Account
  nickname: bluth_co
  just_once: True
  fields:
      Name: The Bluth Company
      Description: Solid as a rock
      NumberOfEmployees: 6

- object: Contact
  nickname: Michael
  just_once: True
  fields:
      FirstName: Michael
      LastName: Bluth
      AccountId:
          reference: bluth_co

# Highly randomized objects
- object: Account
  fields:
      Name:
          fake: Company
      Description:
          fake: CatchPhrase
      BillingStreet:
          fake: StreetAddress
      BillingCity:
          fake: City
      BillingState:
          fake: state
      BillingPostalCode:
          fake: Postalcode
      BillingCountry: Canada
      ShippingStreet:
          fake: StreetAddress
      ShippingCity:
          fake: City
      ShippingState:
          fake: State
      ShippingPostalCode:
          fake: PostalCode
      ShippingCountry:
          fake: Country
      Phone:
          fake: PhoneNumber
      Fax:
          fake: PhoneNumber
      Website:
          fake: uri
      NumberOfEmployees:
          random_number:
              min: 0
              max: 200000
      AccountNumber:
          random_number:
              min: 0
              max: 10000000

- object: Contact
  fields:
      Salutation:
          fake: prefix
      FirstName:
          fake: FirstName
      LastName:
          fake: LastName
      Email:
          fake: email
      Phone:
          fake: PhoneNumber
      MobilePhone:
          fake: PhoneNumber
      Title:
          fake: job
      Birthdate:
          date_between:
              start_date: -50y
              end_date: -20y
      AccountId:
          reference: Account

- object: Opportunity
  count:
      random_number:
          min: 3
          max: 5
  fields:
      Name: ${{fake.word}} Opportunity
      CloseDate:
          date_between:
              start_date: -30d
              end_date: +180d
      Amount:
          random_number:
              min: 10
              max: 200
      StageName:
          random_choice:
              - choice:
                    probability: 60%
                    pick: Closed Won
              - choice:
                    probability: 20%
                    pick: In Progress
              - choice:
                    probability: 60%
                    pick: New
      AccountId:
          reference: Account
