name: SFDX Integration Test

on:
    workflow_call:
        inputs:
            sfdx-release-channel:
                required: false
                type: string
                default: stable
        secrets:
            CUMULUSCI_ORG_packaging:
                required: true
            CUMULUSCI_SERVICE_github:
                required: true
            CCITEST_APP_KEY:
                required: true
            SFDX_CLIENT_ID:
                required: true
            SFDX_HUB_KEY:
                required: true
            SFDX_HUB_KEY_BASE64:
                required: true
            SFDX_HUB_USERNAME:
                required: true

env:
    CUMULUSCI_ORG_scratch: '{"config_file": "orgs/dev.json", "scratch": true}'
    CUMULUSCI_ORG_packaging: ${{ secrets.CUMULUSCI_ORG_packaging }}
    CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
    GITHUB_APP_ID: 129383
    GITHUB_APP_KEY: ${{ secrets.CCITEST_APP_KEY }}
    SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
    SFDX_HUB_KEY: ${{ secrets.SFDX_HUB_KEY }}
    SFDX_HUB_KEY_BASE64: ${{ secrets.SFDX_HUB_KEY_BASE64 }}
    SFDX_HUB_USERNAME: ${{ secrets.SFDX_HUB_USERNAME }}

jobs:
    test_release:
        name: "Test SFDX CLI"
        runs-on: SFDO-Tooling-Ubuntu
        concurrency: release
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
                  cache: pip
                  cache-dependency-path: "pyproject.toml"
            - name: Set up uv
              uses: SFDO-Tooling/setup-uv@main
              with:
                  version: "0.5.0"
                  enable-cache: true
            - name: Install Python dependencies
              run: uv sync
            - name: Install Salesforce CLI
              env:
                  CHANNEL: ${{ inputs.sfdx-release-channel }}
              run: |
                  mkdir sfdx
                  wget -qO- https://developer.salesforce.com/media/salesforce-cli/sf/channels/$CHANNEL/sf-linux-x64.tar.xz | tar xJ -C sfdx --strip-components 1
                  echo $(realpath sfdx/bin) >> $GITHUB_PATH
            - name: Authenticate Dev Hub
              run: |
                  sf plugins --core
                  echo $SFDX_HUB_KEY_BASE64 | base64 --decode > sfdx.key
                  sf org login jwt --client-id $SFDX_CLIENT_ID --jwt-key-file sfdx.key --username $SFDX_HUB_USERNAME --set-default-dev-hub --alias hub
            - name: Check out CumulusCI-Test
              run: |
                  git clone https://github.com/SFDO-Tooling/CumulusCI-Test
            - name: Run ci_feature flow
              run: |
                  cd CumulusCI-Test
                  uv run cci flow run ci_feature --org scratch --delete-org
            - name: Run ci_beta flow
              run: |
                  cd CumulusCI-Test
                  uv run cci flow run ci_beta --org scratch --delete-org
            - name: Run ci_master flow
              run: |
                  cd CumulusCI-Test
                  uv run cci flow run ci_master --org scratch --delete-org
            - name: Run release_beta flow
              run: |
                  export SFDX_HUB_KEY="$(echo $SFDX_HUB_KEY_BASE64 | base64 --decode)"
                  cd CumulusCI-Test
                  uv run cci flow run release_beta --org packaging
